sudo: false
dist: trusty
cache: 
  apt: true
  directories:
    - $HOME/.deps
notifications:
  email: false
  slack:
    rooms:
      secure: FO4vtIe+YSl6xpJVmNzSOvef5RQxOjuUGJ02zhRrkBK3DOQMP2pOjIRIyEq6m0xx+BVK5UoLl8ACFS5e5P0wJOE7Bvl963yonKgK+sGutEGck5EmroBLCln9KvXkYaBElMgDZBZDm8q9ValjVwB2ym/aP82//6LLnCeVRBMThjE=
    on_success: change
    on_failure: always
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "VR/Ts9vkdBqrE22XaT4IrREJB7k0Ml60U+ek0VeVHQTAYGjL+KP13ocoTjBEIEo+iKbUJdX6pXN3VxKu7VAu2W47qIRi7VRznjH0MOonreV7oLX1s7uXYmxJSVIWjQ3EcKIW9I+Qpd3brTd3BV/ew816hfYJJKC2SU6AIV8RszE="

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env: QF_ARCH=OSX
      language: c++
      compiler: clang
    - os: linux
      language: c++
      compiler: clang
      env: QF_ARCH=x86_64
      addons:
        apt:
          packages:
            - clang-6.0
            - cmake
            - build-essential
            - libsdl2-dev
            - libopenal-dev
            - libjpeg8-dev
            - libvorbis-dev
            - libtheora-dev
            - libfreetype6-dev
            - zlib1g-dev
            - libcurl4-gnutls-dev
            - libstdc++-7-dev
        coverity_scan:
          project:
            name: "Qfusion/qfusion"
            description: "Build submitted via Travis CI"
          notification_email: vluchits@gmail.com
          build_command_prepend: "cd source && cov-configure --comptype clangcc --compiler clang && cov-configure --comptype clangcxx --compiler clang++ && export SDL2DIR=$HOME/.deps/$QF_ARCH && cmake ."
          build_command: "make -j8"
          branch_pattern: ci
    - dist: precise
      language: android
      env: QF_ARCH=android
      jdk: oraclejdk7
      android:
        components:
          - build-tools-21.0.2
          - android-19

install:
  - if [[ "$QF_ARCH" == "android" ]] && [ ! -e "$HOME/.deps/android-ndk-r11c" ]; then curl -L http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip >ndk.zip && unzip ndk.zip -d $HOME/.deps &> /dev/null && rm ndk.zip; fi
  - if [[ "$QF_ARCH" == "android" ]]; then export NDK_HOME=$HOME/.deps/android-ndk-r11c && export PATH="$PATH:$NDK_HOME"; fi
  - if [[ "$QF_ARCH" == "x86_64" ]]; then export CC=clang CXX=clang++; fi
  - cd "$TRAVIS_BUILD_DIR/source"
  - if [[ "$QF_ARCH" == "x86_64" ]]; then cmake .; fi
  - if [[ "$QF_ARCH" == "OSX" ]]; then cmake -G Xcode .; fi
  - if [[ "$QF_ARCH" == "android" ]]; then mkdir -p build/libs && cd ../platforms/android/projects/qfusion/jni && ln -s ../../../../../libsrcs libsrcs && ln -s ../../../../../third-party third-party && ln -s ../../../../../source source && ln -s ../../../../../icons icons; fi
  - cd "$TRAVIS_BUILD_DIR"

script:
  - cd source
  - if [[ "$QF_ARCH" == "x86_64" ]]; then make -j8; fi
  - if [[ "$QF_ARCH" == "OSX" ]]; then xcodebuild -project qfusion.xcodeproj/ -jobs 4 -configuration Release -target ALL_BUILD; fi
  - if [[ "$QF_ARCH" == "android" ]]; then cd ../platforms/android/projects/qfusion/jni && ndk-build -j8 && cd "$TRAVIS_BUILD_DIR/source" && cp -Rd ../platforms/android/projects/qfusion/libs/* build/; fi

before_deploy:
  - cd build
  - echo "${TRAVIS_COMMIT}" >commit.txt
  - if [[ "$QF_ARCH" == "OSX" ]]; then cd Release && tar -czvf ../../tmp.tar.gz *.app && cd ..; fi
  - if [[ "$QF_ARCH" != "OSX" ]]; then tar -czvf ../tmp.tar.gz * --exclude *.a --exclude base*/*.a libs/*.a; fi
  - cd ..
  - mv tmp.tar.gz ${QF_ARCH}-Release.tar.gz

deploy:
  provider: releases
  api_key:
    secure: QJZp/MxExRLxtb/vBVNPjnavK/VlveFY5McQOi8qaSa3n30Rihlnlg7XuvAvwTY6zvpEAJcTlxFYh6T4zM2SRuql3XE2uBWFAsrhvw44JhqiSgZZepGu31eWPor4OeqEwuofXjXBzkz+m3xAOtpjnlKD/8crcMXnAlut/10jUoM=
  skip_cleanup: true
  file_glob: true
  file: "*-Release.tar.gz"
  overwrite: true
  on:
    repo: Qfusion/qfusion
    tags: true
